Repository nginx-proxy/nginx-proxy, pull requests merged in 2021-05, with the labels that each got.

#1185 Set proper X-Forwarded-Ssl for SSL-terminated setups
  nginx.tmpl
Labels: type/fix

#1619 Fix broken create_server_certificate.sh
  test/certs/create_server_certificate.sh
Labels: type/test

#1620 Make server_tokens configurable per virtual-host
  README.md
  nginx.tmpl
  test/conftest.py
  test/test_headers/certs/web-server-tokens-off.nginx-proxy.tld.crt
  test/test_headers/certs/web-server-tokens-off.nginx-proxy.tld.key
  test/test_headers/test_http.py
  test/test_headers/test_http.yml
  test/test_headers/test_https.py
  test/test_headers/test_https.yml
Labels: kind/feature request

#1609 Honor VIRTUAL_PORT + DEBUG flag + fallback entry
  README.md
  nginx.tmpl
  test/test_debug/test_proxy-debug-flag.py
  test/test_debug/test_proxy-debug-flag.yml
  test/test_debug/test_server-debug-flag.py
  test/test_debug/test_server-debug-flag.yml
  test/test_multiple-ports/test_VIRTUAL_PORT-single-different-from-single-port.py
  test/test_multiple-ports/test_VIRTUAL_PORT-single-different-from-single-port.yml
Labels: type/feat, type/fix
