Repository nginx-proxy/nginx-proxy, pull requests merged in 2021-04, with the labels that each got.

#1470 Enable multi-architecture docker image builds
  Dockerfile
  Dockerfile.alpine
Labels: area/dockerfile

#1538 Update docker-entrypoint.sh comment on DHPARAM default key size
  README.md
  docker-entrypoint.sh
Labels: area/docs

#1332 Will fix spelling
  README.md
Labels: area/docs

#1184 Update README.md - sample yml needed expose option
  README.md
Labels: area/docs

#1145 Clarify default host usage
  README.md
Labels: area/docs

#1505 Update README.md
  README.md
Labels: area/docs

#1599 Remove Google Forum Link from Issue Template
  .github/ISSUE_TEMPLATE.md
Labels: area/docs

#1601 Bump docker-gen from 0.7.4 to 0.7.6
  Dockerfile
  Dockerfile.alpine
Labels: area/chore, area/dockerfile

#1572 Travis to GitHub actions
  .github/workflows/test.yml
  Makefile
  README.md
  test/README.md
  test/conftest.py
  test/pytest.ini
  test/requirements/Dockerfile-nginx-proxy-tester
  test/requirements/README.md
  test/requirements/build.sh
  test/requirements/python-requirements.txt
  test/requirements/web/webserver.py
  test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py
  test/test_custom/test_location-per-vhost.py
  test/test_default-host.yml
  test/test_dockergen/test_dockergen_v2.py
  test/test_dockergen/test_dockergen_v3.py
  test/test_events.py
  test/test_ssl/test_dhparam.py
  test/test_ssl/test_dhparam_generation.py
  test/test_ssl/test_wildcard.py
  test/test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py
  test/test_wildcard_host.py
Labels: area/ci

#973 Upd: Boost worker_connections from 1024 to 10240.
  Dockerfile
  Dockerfile.alpine
Labels: area/dockerfile

#1263 Change dhparam positional args to be inherited vars, standardize naming
  docker-entrypoint.sh
  generate-dhparam.sh
Labels: type/fix

#1557 Remove scoped IPv6 addresses from resolvers (fix #1424)
  README.md
  docker-entrypoint.sh
Labels: type/fix
