Repository nginx-proxy/nginx-proxy, pull requests merged in 2021-09, with the labels that each got.

#1760 Ease version check on python docker module for tests
  test/conftest.py
Labels: type/ci

#1770 Use path context
  .github/workflows/dockerhub.yml
Labels: type/ci, type/build, type/fix

#1775 fix link
  README.md
Labels: type/docs
