Repository nginx-proxy/nginx-proxy, pull requests merged in 2021-07, with the labels that each got.

#1607 Support for path-based routing
  README.md
  nginx.tmpl
  test/test_events.py
  test/test_virtual-path/test_virtual_paths.py
  test/test_virtual-path/test_virtual_paths.yml
Labels: type/feat

#1698 Build and push the dev branch to Dockerhub
  .github/workflows/dockerhub.yml
Labels: type/build

#1708 docs: remove unnecessary word
  README.md
Labels: type/docs
