Repository nginx-proxy/nginx-proxy, pull requests merged in 2023-12, with the labels that each got.

#2278 feat: experimental HTTP/3 support + optional HTTP/2 disabling
  README.md
  nginx.tmpl
  test/test_http2/test_http2_global_disabled.py
  test/test_http2/test_http2_global_disabled.yml
  test/test_http3/test_http3_global_disabled.py
  test/test_http3/test_http3_global_disabled.yml
  test/test_http3/test_http3_global_enabled.py
  test/test_http3/test_http3_global_enabled.yml
  test/test_http3/test_http3_vhost.py
  test/test_http3/test_http3_vhost.yml
  test/test_ssl/test_hsts.py
  test/test_ssl/test_hsts.yml
Labels: type/feat

#2274 New AWS SSL policies
  README.md
  nginx.tmpl
Labels: type/feat

#2338 fix: TLS 1.3 security policies
  README.md
  nginx.tmpl
Labels: type/fix, type/feat

#2245 ci: image build and publish workflow update
  .github/workflows/build-publish.yml
  Dockerfile.debian
  Makefile
Labels: type/ci

#2347 fix #2310
  nginx.tmpl
Labels: type/fix

#2350 Fix test case assertion depending on python version
  test/test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py
Labels: type/test

#2349 Tests: support custom 'docker compose' command
  test/README.md
  test/conftest.py
Labels: status/pr-needs-docs, type/test

#2356 test: revert "Fix test" and "Sleep longer"
  test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py
Labels: type/test

#2357 docs: split documentation
  README.md
  docs/README.md
Labels: type/docs

#2359 refactor: cleanup dockerfiles
  Dockerfile.alpine
  Dockerfile.debian
  app/Procfile
Labels: type/build

#2358 feat: enable proxy_buffering
  docs/README.md
  nginx.tmpl
Labels: type/feat
