Repository nginx-proxy/nginx-proxy, pull requests merged in 2023-02, with the labels that each got.

#1179 Allow complete override of location blocks
  README.md
  nginx.tmpl
  test/test_location-override.py
  test/test_location-override.vhost.d/explicit-nonroot.nginx-proxy.test_8d960560c82f4e6c8b1b0f03eb30a1afd00e5696_location_override
  test/test_location-override.vhost.d/explicit-root-hash-and-nohash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
  test/test_location-override.vhost.d/explicit-root-hash-and-nohash.nginx-proxy.test_location_override
  test/test_location-override.vhost.d/explicit-root-hash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
  test/test_location-override.vhost.d/explicit-root-nohash.nginx-proxy.test_location_override
  test/test_location-override.vhost.d/implicit-root-hash-and-nohash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
  test/test_location-override.vhost.d/implicit-root-hash-and-nohash.nginx-proxy.test_location_override
  test/test_location-override.vhost.d/implicit-root-hash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
  test/test_location-override.vhost.d/implicit-root-nohash.nginx-proxy.test_location_override
  test/test_location-override.yml
Labels: type/feat

#2183 fix: Sort networks and ports before iterating
  nginx.tmpl
Labels: type/fix

#2184 build: dockergen 0.10.0 -> 0.10.1
  Dockerfile
  Dockerfile.alpine
Labels: type/build, scope/dockerfile
