Repository nginx-proxy/nginx-proxy, pull requests merged in 2023-04, with the labels that each got.

#2214 fix: Remove `default_server` listen option from fallback server
  nginx.tmpl
  test/test_fallback.data/custom-fallback.conf
  test/test_fallback.data/custom-fallback.yml
  test/test_fallback.py
Labels: type/fix

#2220 build: dockergen 0.10.3 -> 0.10.4
  Dockerfile
  Dockerfile.alpine
Labels: type/build, scope/dockerfile

#2226 ci: maintain GitHub Actions with Dependabot
  .github/dependabot.yml
Labels: type/ci

#2229 ci: rename build / publish workflow
  .github/workflows/build-publish.yml
Labels: type/ci
