Repository nginx-proxy/nginx-proxy, pull requests merged in 2024-01, with the labels that each got.

#2369 test: install docker compose in nginx-proxy-tester image
  test/README.md
  test/requirements/Dockerfile-nginx-proxy-tester
Labels: type/test

#2372 build: add the openssl cli back to the alpine image
  Dockerfile.alpine
Labels: type/build

#2364 feat: keepalive auto setting
  docs/README.md
  nginx.tmpl
  test/test_keepalive.py
  test/test_keepalive.yml
Labels: type/feat

#2321 Add support for grpcs protocol
  nginx.tmpl
Labels: type/feat
