Repository nginx-proxy/nginx-proxy, pull requests merged in 2024-11, with the labels that each got.

#2525 feat: nginx-proxy debug endpoint
  docs/README.md
  nginx.tmpl
  test/test_debug_endpoint/test_global.py
  test/test_debug_endpoint/test_global.yml
  test/test_debug_endpoint/test_per_container.py
  test/test_debug_endpoint/test_per_container.yml
Labels: type/feat

#2534 refactor: move $globals.ENV to $globals.config
  docs/README.md
  nginx.tmpl
Labels: type/feat

#2537 fix: do not render regexp hostname in debug endpoint response
  nginx.tmpl
  test/test_debug_endpoint/test_global.py
  test/test_debug_endpoint/test_global.yml
Labels: type/fix

#2538 test: add test for DISABLE_ACCESS_LOGS
  test/test_logs/test_log_disabled.py
  test/test_logs/test_log_disabled.yml
Labels: type/test

#2546 feat: enable keepalive by default
  docs/README.md
  nginx.tmpl
  test/test_keepalive.yml
Labels: type/feat

#2547 docs: remove experimental label for http loadbalance
  docs/README.md
Labels: type/docs

#2551 chore: changes from upstream docker install
  test/requirements/Dockerfile-nginx-proxy-tester
Labels: type/ci
