Repository nginx-proxy/nginx-proxy, pull requests merged in 2024-02, with the labels that each got.

#2383 Add s390x support
  .github/workflows/build-publish.yml
Labels: type/ci

#2387 fix: set worker_rlimit_nofile to (worker_connections x 2)
  Dockerfile.alpine
  Dockerfile.debian
Labels: type/fix

#2388 fix: add non standard port to Host header
  nginx.tmpl
Labels: type/fix

#2389 feat: define basic auth for virtual path
  docs/README.md
  nginx.tmpl
Labels: type/feat

#2197 Add more control over log_format config directive
  docs/README.md
  nginx.tmpl
  test/test_log_json.py
  test/test_log_json.yml
  test/test_log_json_format.py
  test/test_log_json_format.yml
Labels: type/feat

#2396 build: revert nginx to 1.25.3
  Dockerfile.alpine
  Dockerfile.debian
  README.md
  test/certs/create_server_certificate.sh
Labels: type/build, type/fix

#2404 docs: add comment about host network to compose example
  docker-compose.yml
Labels: type/docs
