Repository nginx-proxy/nginx-proxy, pull requests merged in 2025-08, with the labels that each got.

#2641 feat: pass X-Real-IP header to gRPC Backend
  nginx.tmpl
Labels: type/feat

#2648 ci: add workflows permissions
  .github/workflows/build-publish-dispatch.yml
  .github/workflows/build-publish.yml
  .github/workflows/dockerhub-description.yml
  .github/workflows/test.yml
Labels: type/ci

#2649 fix: prevent incorrect loading of wildcard domains in vhost configuration
  .github/workflows/test.yml
  nginx.tmpl
  test/requirements/python-requirements.txt
  test/test_custom/my_custom_proxy_settings_baz.conf
  test/test_custom/test_defaults.py
  test/test_custom/test_defaults.yml
  test/test_custom/test_location-defaults.py
  test/test_custom/test_location-defaults.yml
  test/test_custom/test_location-per-vhost.py
  test/test_custom/test_location-per-vhost.yml
  test/test_custom/test_per-vhost.py
  test/test_custom/test_per-vhost.yml
  test/test_custom/test_proxy-wide.py
  test/test_custom/test_proxy-wide.yml
  test/test_dockergen/test_dockergen_network_segregation-custom-label.py
  test/test_dockergen/test_dockergen_network_segregation.py
Labels: type/fix

#2650 docs: add precisions to multi container compose file
  docker-compose-separate-containers.yml
Labels: type/docs
